site_name: Algorithms App
site_author: Nicholas Mendez
site_favicon: assets/images/favicon.ico
site_url: https://algorithms-90a10.firebaseapp.com

theme: 'material'

pages:
  - Introduction: index.md
  - Dynamic Programming: dynamic.md
  - Asymptotic Notation: asym.md
  - Backtracking: back.md
  - Branch and Bound: branch.md
  - Optimization Problems: optim.md


# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)

# Options
extra:
  version: 0.2.0
  logo: assets/images/android-icon-192x192.png
  github:
    download_release: true
  author:
    github: snickdx
  palette:
    primary: 'teal'
    accent: 'amber'
  feature:
    tabs: false

## Repository
repo_name: Algo-Reference
repo_url: https://github.com/Snickdx/algo-reference